version: '3.9'

services:
  web:
    build: .
    # command: python ./app/ch3/manage.py runserver 0.0.0.0:8000
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000  # new
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-)fzcjgioeojrhp1i2h*y%zxv7w^9x20=0g(dtxxlhfq&$9@ps-"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
